language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build


matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix format --check-formatted
  - mix credo --strict

before_cache:
  - mix deps.clean --all --build
  - mix clean --build