language: elixir

cache:
  directories:
    - ~/.mix
    - _build


matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 18.3
      elixir: 1.4

install:
  - mix deps.get

script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test

before_cache:
  - mix deps.clean --all --build
  - mix clean --build